/*pass = pravna123 */

INSERT INTO `pravnainformatika`.`users` (`id`, `address`, `city`, `email`, `first_name`, `last_name`, `password`, `phone`, `username`) VALUES ('1', 'UTC--2020-04-21T20-20-11.997000000Z--eefff9227c4400a37f4cc225fddf7f5afd5c6c45.json', 'Trg Dositeja Obradovića 6, Novi Sad 106314', 'peraperic@gmail.com', 'Pera', 'Peric', '$2a$10$58KqUFFrDj/tt8N0TpB5lOxZ.UpLPnmtRbf6ipzb5zJO2h3cEAVIG', '381641234567', 'username1');
INSERT INTO `pravnainformatika`.`users` (`id`, `address`, `city`, `email`, `first_name`, `last_name`, `password`, `phone`, `username`) VALUES ('2', 'UTC--2020-04-21T20-21-46.46000000Z--8f841a042bb8f2bae139b83a21fc286c500499bc.json', 'Trg Dositeja Obradovića 87, Novi Sad 106314', 'ivan@gmail.com', 'Ivan', 'Ivanic', '$2a$10$XXdYI6/AiYizAqFX0RjHqOkCwTozc5KluAKDNO./14wXfybTZCHfe', '38112134567', 'username2');

INSERT INTO `pravnainformatika`.`roba` (`id`, `broj_primera_kupac`, `broj_primeraka`, `cena`, `deo_robe`, `izvrsitelj_isporuke`, `kolicina`, `kupac_odgovoran`, `naziv`, `nesaobraznost_zamenom`, `opis`, `roba_prodata`, `rok_isporuke`, `rok_isporuke_max`, `rok_od_prelaska_rizika_na_kupca`, `rok_odustanak`, `rok_vracanja_novca`, `rok_vracanja_robe`, `troskove_snosi`, `troskovi_odustanak`, `uputstvo`, `vlasnik_id`, `pravo_saobraznost`) VALUES ('1', '1', '3', '1200', 'POSLEDNJI', 'Post Express ili licno na teritoriji Novog Sada', '1', b'0', 'Knjiga - kolekcija Gospodar Prstenova ', b'0', 'Tolkinove fantastične povesti Srednjeg sveta nastale su kada je on, kao i mnogi očevi, počeo da izmišlja priče za svoje sinove, priče koje su polako izrastale u stvarnost čitavog jednog nepostojećeg sveta. ', b'0', '3', '5', '2', '2', '2', '2', 'KUPAC', 'KUPAC', b'0', b'1', b'0');
INSERT INTO `pravnainformatika`.`roba` (`id`, `broj_primera_kupac`, `broj_primeraka`, `cena`, `deo_robe`, `izvrsitelj_isporuke`, `kolicina`, `kupac_odgovoran`, `naziv`, `nesaobraznost_zamenom`, `opis`, `roba_prodata`, `rok_isporuke`, `rok_isporuke_max`, `rok_od_prelaska_rizika_na_kupca`, `rok_odustanak`, `rok_vracanja_novca`, `rok_vracanja_robe`, `troskove_snosi`, `troskovi_odustanak`, `uputstvo`, `vlasnik_id`, `pravo_saobraznost`) VALUES ('2', '1', '3', '500', 'PRVI', 'Post Express ili licno na teritoriji Novog Sada', b'1', b'1', 'Knjiga - Svet leda i vatre', b'1', 'Džordža R. R. Martin', b'0', '2', '6', '2', '2', '2', '2', 'PRODAVAC', 'KUPAC', b'0', b'1', b'0');
INSERT INTO `pravnainformatika`.`roba` (`id`, `broj_primera_kupac`, `broj_primeraka`, `cena`, `deo_robe`, `izvrsitelj_isporuke`, `kolicina`, `kupac_odgovoran`, `naziv`, `nesaobraznost_zamenom`, `opis`, `roba_prodata`, `rok_isporuke`, `rok_isporuke_max`, `rok_od_prelaska_rizika_na_kupca`, `rok_odustanak`, `rok_vracanja_novca`, `rok_vracanja_robe`, `troskove_snosi`, `troskovi_odustanak`, `uputstvo`, `vlasnik_id`, `pravo_saobraznost`) VALUES ('3', '1', '3', '800', 'PRVI', 'Post Express ili licno na teritoriji Novog Sada', b'1', b'1', 'Knjiga - Poslednja želja', b'1', 'Upoznajte Geralta, naočitog lovca bele kose i prodornog pogleda. Nadaleko je čuven zbog cinizma i nepoštovanja autoriteta, muževne privlačnosti i harizme. ', b'0', '3', '6', '2', '2', '2', '2', 'PRODAVAC', 'KUPAC', b'0', '2', b'0');


INSERT INTO `pravnainformatika`.`contractr` (`id`, `address`, `roba_id`, `vlasnik_id`) VALUES ('1', '0xac31284d5071ff4057cec945e7cb01a1873a67b9', '1', '1');
INSERT INTO `pravnainformatika`.`contractr` (`id`, `address`, `roba_id`, `vlasnik_id`) VALUES ('2', '0xd68e2680c2bcc62e44399a219d938b4339c48802', '2', '1');
INSERT INTO `pravnainformatika`.`contractr` (`id`, `address`, `roba_id`, `vlasnik_id`) VALUES ('3', '0x8271d0b41efe95fce2bf426bc4bb5fc628fc43a8', '3', '2');